# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
   config.vm.box = "generic/debian10"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
   config.vm.network "forwarded_port", guest: 80, host: 8080
   config.vm.network "forwarded_port", guest: 81, host: 8081

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
   config.vm.network "private_network", ip: "192.168.10.11"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder  ".", "/vagrant", disabled: false

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
     vb.name = "lxcdeb1"
     vb.memory = "512"
   end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt purge gnupg
     apt install --reinstall gnupg2
     apt install dirmngr
     apt-get install -y mc lxc-templates lxc bridge-utils
     mkdir -p /home/vagrant/.config/lxc
     sudo echo "lxc.net.0.type = veth" >> /home/vagrant/.config/lxc/root.conf
     sudo echo "lxc.net.0.flags = up" >> /home/vagrant/.config/lxc/root.conf
     sudo echo "lxc.net.0.link = lxcbr0" >> /home/vagrant/.config/lxc/root.conf
     sudo echo "lxc.start.auto = 1" >> /home/vagrant/.config/lxc/root.conf
     sudo echo "dhcp-host=c1,10.0.3.101" >> /home/vagrant/.config/lxc/lxc-dhcp.conf
     sudo echo "dhcp-host=c2,10.0.3.102" >> /home/vagrant/.config/lxc/lxc-dhcp.conf
     sudo echo kernel.unprivileged_userns_clone=1 >> /etc/sysctl.conf
     #sudo echo "vagrant veth lxcbr0 10" >> /etc/lxc/lxc-usernet
     cat > /etc/default/lxc-net <<EOF
     USE_LXC_BRIDGE="true"
     LXC_BRIDGE="lxcbr0"
     LXC_ADDR="10.0.3.1"
     LXC_NETMASK="255.255.255.0"
     LXC_NETWORK="10.0.3.0/24"
     LXC_DHCP_RANGE="10.0.3.200,10.0.3.254"
     LXC_DHCP_MAX="253"
     LXC_DHCP_CONFILE="/home/vagrant/.config/lxc/lxc-dhcp.conf"
     LXC_DOMAIN=""
EOF
     systemctl enable lxc-net
     systemctl start lxc-net
     sudo lxc-create -n c1 -f /home/vagrant/.config/lxc/root.conf -t download -- --dist centos --release 8-Stream --arch amd64 --keyserver "hkp://keyserver.ubuntu.com"
     sudo lxc-create -n c2 -f /home/vagrant/.config/lxc/root.conf -t download -- --dist centos --release 8-Stream --arch amd64 --keyserver "hkp://keyserver.ubuntu.com"
     sudo lxc-autostart -a
     sudo sleep 20
     sudo iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 80 -j DNAT --to-destination 10.0.3.101
     sudo iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 81 -j DNAT --to-destination 10.0.3.102
     sudo lxc-attach -n c1 -- sudo yum install -y httpd
     sudo lxc-attach -n c1 -- systemctl start httpd
     sudo lxc-attach -n c2 -- sudo yum install -y php
     sudo lxc-attach -n c2 -- sudo systemctl start php-fpm
     sudo curl -o /home/vagrant/httpd.conf https://raw.githubusercontent.com/KatJIeTTo/devops-hometask/main/task-02/httpd.conf
     sudo curl -o /home/vagrant/info.php https://raw.githubusercontent.com/KatJIeTTo/devops-hometask/main/task-02/info.php
     sudo rm /var/lib/lxc/c2/rootfs/etc/httpd/conf/httpd.conf
     sudo cp /home/vagrant/httpd.conf /var/lib/lxc/c2/rootfs/etc/httpd/conf/
     sudo cp /home/vagrant/info.php /var/lib/lxc/c2/rootfs/var/www/html
     sudo lxc-attach -n c2 -- sudo systemctl restart httpd
   SHELL
end
