---
- name: Lxc Install and configurate
  hosts: all
  become: yes

  tasks:

  - name: Lxc create c1
    become: yes
    lxc_container:
       name: c1
       container_log: true
       template: download
       state: started
       conf: 
         home/vagrant/.config/lxc/root.conf
       template_options: --dist centos --release 8-Stream --arch amd64 --no-validate --keyserver "hkp://keyserver.ubuntu.com"
       container_comand: |
         sudo yum install -y httpd
         systemctl start httpd

  - name: Lxc create c2
    become: yes
    lxc_container:
       name: c2
       container_log: true
       template: download
       state: stopped
       template_options: --dist centos --release 8-Stream --arch amd64 --no-validate --keyserver "hkp://keyserver.ubuntu.com"