---
- name: Lxc Install and configurate
  hosts: all
  become: yes

  tasks:

  - name: Lxc create c1
    become: yes
    lxc_container:
       name: c1
       conf: /home/vagrant/.config/lxc/root.conf
       container_log: true
       template: download
       state: started
       template_options: --dist centos --release 8-Stream --arch amd64 --no-validate --keyserver "hkp://keyserver.ubuntu.com"

  - name: Lxc create c2
    become: yes
    lxc_container:
       name: c2
       container_log: true
       template: download
       state: stopped
       template_options: --dist centos --release 8-Stream --arch amd64 --no-validate --keyserver "hkp://keyserver.ubuntu.com"