# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian11"

   config.vm.network "forwarded_port", guest: 80, host: 8080
   config.vm.network "forwarded_port", guest: 81, host: 8081

   config.vm.network "private_network", ip: "192.168.10.13"
   
   config.vm.synced_folder  ".", "/vagrant", disabled: false

   config.vm.provider "virtualbox" do |vb|
     vb.name = "ansdeb02"
     vb.memory = "1024"
    end
    

   config.vm.provision "shell", inline: <<-SHELL
     apt install sshpass
    SHELL
   
   config.vm.provision :ansible_local do |ansible|
      ansible.playbook = "playbook02.yml"
      ansible.limit          = "all"
      ansible.become = true
    end 

end
